# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-01 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weclub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity',
            field=models.CharField(blank=True, choices=[('LIGHT', 'LIGHT'), ('MODERATE', 'MODERATE'), ('VIGOROUS', 'VIGOROUS')], max_length=255, null=True),
        ),
    ]
