# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-01 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weclub', '0002_user_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='goal_body',
            field=models.CharField(blank=True, choices=[('ATHLETIC', 'ATHLETIC'), ('FIT', 'FIT'), ('AVERAGE', 'AVERAGE')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='goal_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
