# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-02-02 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weclub', '0003_auto_20200201_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField()),
                ('message_source', models.BooleanField()),
                ('body', models.TextField()),
                ('time', models.CharField(max_length=255)),
            ],
        ),
    ]
